
package views;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import models.Purchases;
import models.Sales;
import models.SalesDao;

public class PrintVentas extends javax.swing.JFrame {

    Sales sale = new Sales();
    SalesDao saleDao = new SalesDao();
    DefaultTableModel model = new DefaultTableModel();

    public PrintVentas(int id) throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Factura de Venta");
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        txt_invoice.setText("" + id);
        listAllSalesDetails(id);
        calculateSale();
        
    }
//Para recibir le id que se envía desde el controlador Purchases Controller
    public void listAllSalesDetails(int id) throws SQLException {
        List<Sales> list = saleDao.listSalesDetailsquery(id);
        System.out.println("Tamaño de la lista de ventas: " + list.size());  // DEPURACIÓN

if (list.isEmpty()) {
    JOptionPane.showMessageDialog(this, "No se encontraron detalles de venta con el ID: " + id);
}
        model = (DefaultTableModel) sale_details_table.getModel();
        model.setRowCount(0);
        
        Object[] row = new Object[7];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getProduct_name();
            row[1] = list.get(i).getSale_quantity();
            row[2] = list.get(i).getSale_price();
            row[3] = list.get(i).getSale_subtotal();
            row[4] = list.get(i).getEmployee_name();
            row[5] = list.get(i).getCustomer_name();
            row[6] = list.get(i).getSale_date();
            model.addRow(row);
                    }
        sale_details_table.setModel(model);
        
    }
    
    //Calcular el total
      public void calculateSale() {
        double total = 0.00;
        int numRow = sale_details_table.getRowCount();
        for (int i = 0; i < numRow; i++) {
            //Pasar el índice de la a columna que sumará
            total = total + Double.parseDouble(String.valueOf(sale_details_table.getValueAt(i, 3)));
        }
        txt_total_sale.setText("" + total);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        form_print = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_invoice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sale_details_table = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txt_total_sale = new javax.swing.JTextField();
        btn_print_sale = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        form_print.setBackground(new java.awt.Color(255, 204, 153));
        form_print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconoNutrir.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, Short.MAX_VALUE)
        );

        form_print.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 70));

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nutrir");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        txt_invoice.setEditable(false);
        jPanel1.add(txt_invoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 110, -1));

        form_print.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 580, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("DETALLES DE LA VENTA:");
        form_print.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        sale_details_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio", "Subtotal", "Empleado", "Cliente", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(sale_details_table);
        if (sale_details_table.getColumnModel().getColumnCount() > 0) {
            sale_details_table.getColumnModel().getColumn(0).setMinWidth(100);
            sale_details_table.getColumnModel().getColumn(5).setMinWidth(110);
            sale_details_table.getColumnModel().getColumn(6).setMinWidth(80);
        }

        form_print.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 620, 220));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("TOTAL:");
        form_print.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, -1));

        txt_total_sale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_total_sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_total_saleActionPerformed(evt);
            }
        });
        form_print.add(txt_total_sale, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 110, -1));

        getContentPane().add(form_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 520));

        btn_print_sale.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_print_sale.setText("IMPRIMIR");
        btn_print_sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_print_saleActionPerformed(evt);
            }
        });
        getContentPane().add(btn_print_sale, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_total_saleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_total_saleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_total_saleActionPerformed
    //Método para imprimir la factura
    private void btn_print_saleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_print_saleActionPerformed
    PrinterJob job = PrinterJob.getPrinterJob();
    job.setJobName("Factura de Venta");

    job.setPrintable(new Printable() {

        public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
            if (pageIndex > 0) {
                return Printable.NO_SUCH_PAGE;
            }
            Graphics2D g2 = (Graphics2D) graphics;
            g2.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
            form_print.printAll(g2);
            return Printable.PAGE_EXISTS;
        }
    });

    boolean returningResult = job.printDialog();
    if (returningResult) {
        try {
            job.print();
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(this, "Error al imprimir: " + ex.getMessage());
        }
    }



    }//GEN-LAST:event_btn_print_saleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_print_sale;
    private javax.swing.JPanel form_print;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable sale_details_table;
    public javax.swing.JTextField txt_invoice;
    public javax.swing.JTextField txt_total_sale;
    // End of variables declaration//GEN-END:variables
}
